#!/bin/bash

trap "[ -d '/tmp/backup' ] && rm -rf '/tmp/backup'; sv start tomcat7 > /dev/null" EXIT

sv stop tomcat7 > /dev/null
if [ -d /tmp/backup ]; then
  rm -rf /tmp/backup || exit 255
fi

mkdir -p /tmp/backup && cd $_ || exit 255

cp -a /usr/share/solr/node/solr/* /tmp/backup/ || exit 255
sv start tomcat7 > /dev/null || exit 255

tar -c */data/ | bzip2 -1
