#!/bin/bash

trap "[ -d '/tmp/backup' ] && rm -rf '/tmp/backup'; /opt/start-solr.sh > /dev/null" EXIT

/opt/stop-solr.sh > /dev/null
if [ -d /tmp/backup ]; then
  rm -rf /tmp/backup || exit 255
fi

mkdir -p /tmp/backup && cd $_ || exit 255

cp -a /opt/solr/server/solr/* /tmp/backup/ || exit 255
/opt/start-solr.sh > /dev/null || exit 255

tar -c */data/ | bzip2 -1
